// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - TanStack devtools (dev-only, first), tanstackStart, viteReact, tailwindcss, tsConfigPaths,
//     nitro (build-only using cloudflare as a default target), VITE_* env injection, @ path alias,
//     React/TanStack dedupe, error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

const serverNoExternal = [
  "@supabase/auth-js",
  "@supabase/functions-js",
  "@supabase/postgrest-js",
  "@supabase/realtime-js",
  "@supabase/storage-js",
  "@supabase/supabase-js",
  "accepts",
  "agent-base",
  "append-field",
  "asynckit",
  "axios",
  "body-parser",
  "buffer-from",
  "busboy",
  "bytes",
  "call-bound",
  "call-bind-apply-helpers",
  "call-bind-apply-helpers/functionApply",
  "call-bind-apply-helpers/functionCall",
  "combined-stream",
  "concat-stream",
  "delayed-stream",
  "content-disposition",
  "content-type",
  "cookie",
  "cookie-signature",
  "cors",
  "debug",
  "depd",
  "dotenv",
  "dunder-proto",
  "dunder-proto/get",
  "ee-first",
  "encodeurl",
  "es-define-property",
  "es-errors",
  "es-errors/type",
  "es-object-atoms",
  "es-set-tostringtag",
  "escape-html",
  "etag",
  "express",
  "express-rate-limit",
  "finalhandler",
  "follow-redirects",
  "form-data",
  "forwarded",
  "function-bind",
  "get-intrinsic",
  "get-proto",
  "get-proto/Object.getPrototypeOf",
  "get-proto/Reflect.getPrototypeOf",
  "gopd",
  "fresh",
  "has-symbols",
  "has-tostringtag",
  "helmet",
  "has-tostringtag/shams",
  "hasown",
  "https-proxy-agent",
  "http-errors",
  "iceberg-js",
  "iconv-lite",
  "inherits",
  "ip-address",
  "ipaddr.js",
  "is-promise",
  "merge-descriptors",
  "media-typer",
  "mime-db",
  "mime-types",
  "math-intrinsics",
  "math-intrinsics/abs",
  "math-intrinsics/floor",
  "math-intrinsics/max",
  "math-intrinsics/min",
  "math-intrinsics/pow",
  "math-intrinsics/round",
  "math-intrinsics/sign",
  "ms",
  "multer",
  "negotiator",
  "object-assign",
  "object-inspect",
  "on-finished",
  "once",
  "parseurl",
  "path-to-regexp",
  "proxy-addr",
  "qs",
  "range-parser",
  "raw-body",
  "razorpay",
  "readable-stream",
  "router",
  "safer-buffer",
  "send",
  "serve-static",
  "setprototypeof",
  "side-channel",
  "side-channel-list",
  "side-channel-map",
  "side-channel-weakmap",
  "statuses",
  "streamsearch",
  "toidentifier",
  "type-is",
  "typedarray",
  "unpipe",
  "util-deprecate",
  "vary",
  "wrappy",
];

export default defineConfig({
  vite: {
    ssr: {
      noExternal: serverNoExternal,
    },
  },
  nitro: {
    preset: "vercel",
    traceDeps: serverNoExternal,
  },
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
  },
});
